### ISSUE TITLE
jsonschema 3.2.0 does not satisfy "jsonschema==3.0.*,>=3.0.0"

### ISSUE THREAD

**Issue by fryfrog** [andreasnuesslein/runrestic#21]
Shouldn't a jsonschema version of 3.2.0 satisfy the `>=3.0.0` portion of this from requirements.txt?

```
community/python-jsonschema 3.2.0-1 (93.4 KiB 582.6 KiB) (Installed)
    An implementation of JSON Schema validation for Python
```

```
0 ✓ fryfrog@apollo ~/aur/runrestic $[master] runrestic
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (jsonschema 3.2.0 (/usr/lib/python3.8/site-packages), Requirement.parse('jsonschema==3.0.*,>=3.0.0'), {'runrestic'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/runrestic", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jsonschema==3.0.*,>=3.0.0' distribution was not found and is required by runrestic
```

**Comment by andreasnuesslein** [comment]
@fryfrog obviously I saw the conversation on AUR but thanks for filing anyways.

The setup.py is auto-generated by dephell and apparently it does a mediocre job at that.

I will look into it and I guess create it manually :(
